-- DATABASE: QUẢN LÝ BÁN NÔNG SẢN
CREATE DATABASE IF NOT EXISTS QuanLyNongSan 
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

USE QuanLyNongSan;

-- 1. BẢNG VAI TRÒ 
CREATE TABLE VaiTro (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenVaiTro VARCHAR(50) NOT NULL, -- Admin, Khách hàng, Nhân viên
    MoTa VARCHAR(255),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. BẢNG NGƯỜI DÙNG (Tài khoản)
CREATE TABLE NguoiDung (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenNguoiDung VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    SDT VARCHAR(15),
    MatKhau VARCHAR(255) NOT NULL,
    DiaChi VARCHAR(500),
    NgaySinh DATE,
    GioiTinh ENUM('Nam', 'Nữ', 'Khác'),
    HinhAnh VARCHAR(1000),
    TrangThai BOOLEAN DEFAULT TRUE,
    IDVaiTro INT DEFAULT 2, -- 1: Admin, 2: Khách hàng
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_NguoiDung_VaiTro FOREIGN KEY (IDVaiTro) REFERENCES VaiTro(ID) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. BẢNG TOKEN (Xác thực)
CREATE TABLE Token (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDNguoiDung INT NOT NULL,
    Token VARCHAR(500) NOT NULL,
    LoaiToken ENUM('reset_password', 'verify_email', 'remember_token') NOT NULL,
    NgayHetHan DATETIME NOT NULL,
    TrangThai BOOLEAN DEFAULT TRUE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Token_NguoiDung FOREIGN KEY (IDNguoiDung) REFERENCES NguoiDung(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. BẢNG DANH MỤC SẢN PHẨM
CREATE TABLE DanhMuc (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenDanhMuc VARCHAR(255) NOT NULL,
    MoTa VARCHAR(500),
    HinhAnh VARCHAR(1000),
    ThuTu INT DEFAULT 0,
    TrangThai BOOLEAN DEFAULT TRUE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. BẢNG LOẠI SẢN PHẨM (Phân loại chi tiết)
CREATE TABLE LoaiSanPham (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenLoaiSP VARCHAR(255) NOT NULL,
    MoTa VARCHAR(500),
    IDDanhMuc INT,
    TrangThai BOOLEAN DEFAULT TRUE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_LoaiSanPham_DanhMuc FOREIGN KEY (IDDanhMuc) REFERENCES DanhMuc(ID) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. BẢNG NHÀ CUNG CẤP
CREATE TABLE NhaCungCap (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenNhaCungCap VARCHAR(255) NOT NULL,
    DiaChi VARCHAR(500),
    SDT VARCHAR(15),
    Email VARCHAR(255),
    NguoiLienHe VARCHAR(255),
    GhiChu VARCHAR(1000),
    TrangThai BOOLEAN DEFAULT TRUE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. BẢNG SẢN PHẨM
CREATE TABLE SanPham (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenSanPham VARCHAR(255) NOT NULL,
    MoTa VARCHAR(2000),
    MoTaChiTiet TEXT,
    Gia DECIMAL(18,2) NOT NULL,
    GiaGoc DECIMAL(18,2), -- Giá gốc trước khuyến mãi
    SoLuongTon INT DEFAULT 0,
    DonViTinh VARCHAR(30) NOT NULL,
    HinhAnh VARCHAR(1000),
    XuatXu VARCHAR(100),
    HanSuDung INT, -- Số ngày
    TrongLuong VARCHAR(50),
    ThuongHieu VARCHAR(255),
    LuotXem INT DEFAULT 0,
    LuotBan INT DEFAULT 0,
    DanhGiaTrungBinh DECIMAL(2,1) DEFAULT 0,
    TrangThai BOOLEAN DEFAULT TRUE,
    NoiBat BOOLEAN DEFAULT FALSE,
    IDLoaiSP INT,
    IDNhaCungCap INT,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_SanPham_LoaiSanPham FOREIGN KEY (IDLoaiSP) REFERENCES LoaiSanPham(ID) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT FK_SanPham_NhaCungCap FOREIGN KEY (IDNhaCungCap) REFERENCES NhaCungCap(ID) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. BẢNG HÌNH ẢNH SẢN PHẨM (Nhiều ảnh)
CREATE TABLE HinhAnhSanPham (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDSanPham INT NOT NULL,
    DuongDan VARCHAR(1000) NOT NULL,
    ThuTu INT DEFAULT 0,
    LaAnhChinh BOOLEAN DEFAULT FALSE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_HinhAnhSanPham_SanPham FOREIGN KEY (IDSanPham) REFERENCES SanPham(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. BẢNG KHUYẾN MÃI
CREATE TABLE KhuyenMai (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenKhuyenMai VARCHAR(255) NOT NULL,
    MoTa VARCHAR(1000),
    LoaiKhuyenMai ENUM('phan_tram', 'tien_mat') NOT NULL,
    GiaTriGiam DECIMAL(18,2) NOT NULL,
    GiamToiDa DECIMAL(18,2), -- Giảm tối đa (nếu là %)
    NgayBatDau DATETIME NOT NULL,
    NgayKetThuc DATETIME NOT NULL,
    TrangThai BOOLEAN DEFAULT TRUE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. BẢNG SẢN PHẨM - KHUYẾN MÃI (Áp dụng KM)
CREATE TABLE SanPhamKhuyenMai (
    IDSanPham INT NOT NULL,
    IDKhuyenMai INT NOT NULL,
    GhiChu VARCHAR(500),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (IDSanPham, IDKhuyenMai),
    CONSTRAINT FK_SanPhamKhuyenMai_SanPham FOREIGN KEY (IDSanPham) REFERENCES SanPham(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SanPhamKhuyenMai_KhuyenMai FOREIGN KEY (IDKhuyenMai) REFERENCES KhuyenMai(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. BẢNG VOUCHER (Mã giảm giá)
CREATE TABLE Voucher (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MaVoucher VARCHAR(50) UNIQUE NOT NULL,
    TenVoucher VARCHAR(255) NOT NULL,
    LoaiGiam ENUM('phan_tram', 'tien_mat') NOT NULL,
    GiaTriGiam DECIMAL(18,2) NOT NULL,
    GiamToiDa DECIMAL(18,2),
    DonToiThieu DECIMAL(18,2) DEFAULT 0, -- Giá trị đơn hàng tối thiểu
    SoLuong INT NOT NULL,
    SoLuongDaDung INT DEFAULT 0,
    NgayBatDau DATETIME NOT NULL,
    NgayKetThuc DATETIME NOT NULL,
    TrangThai BOOLEAN DEFAULT TRUE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. BẢNG LỊCH SỬ SỬ DỤNG VOUCHER
CREATE TABLE LichSuVoucher (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDVoucher INT NOT NULL,
    IDNguoiDung INT NOT NULL,
    IDDonHang INT,
    GiaTriGiam DECIMAL(18,2),
    NgaySuDung DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LichSuVoucher_Voucher FOREIGN KEY (IDVoucher) REFERENCES Voucher(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_LichSuVoucher_NguoiDung FOREIGN KEY (IDNguoiDung) REFERENCES NguoiDung(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 13. BẢNG GIỎ HÀNG
CREATE TABLE GioHang (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDNguoiDung INT NOT NULL,
    IDSanPham INT NOT NULL,
    SoLuong INT NOT NULL DEFAULT 1,
    GiaTaiThoiDiem DECIMAL(18,2), -- Giá sản phẩm tại thời điểm thêm
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_GioHang_NguoiDung FOREIGN KEY (IDNguoiDung) REFERENCES NguoiDung(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_GioHang_SanPham FOREIGN KEY (IDSanPham) REFERENCES SanPham(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    UNIQUE KEY unique_cart_item (IDNguoiDung, IDSanPham)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 14. BẢNG ĐƠN HÀNG
CREATE TABLE DonHang (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MaDonHang VARCHAR(50) UNIQUE NOT NULL,
    IDNguoiDung INT,
    TenNguoiNhan VARCHAR(255) NOT NULL,
    SDTNguoiNhan VARCHAR(15) NOT NULL,
    DiaChiGiaoHang VARCHAR(500) NOT NULL,
    ThoiGianGiao VARCHAR(100),
    PhuongThucThanhToan ENUM('COD', 'VNPay', 'MoMo', 'ZaloPay', 'Bank') DEFAULT 'COD',
    PhuongThucVanChuyen ENUM('GHN', 'GHTK', 'Viettel Post', 'Nội thành') DEFAULT 'GHTK',
    TongTien DECIMAL(18,2) NOT NULL,
    PhiVanChuyen DECIMAL(18,2) DEFAULT 0,
    GiamGiaVoucher DECIMAL(18,2) DEFAULT 0,
    IDVoucher INT,
    TongThanhToan DECIMAL(18,2) NOT NULL,
    TrangThai ENUM('cho_xac_nhan', 'da_xac_nhan', 'dang_giao', 'da_giao', 'huy') DEFAULT 'cho_xac_nhan',
    GhiChu VARCHAR(1000),
    NgayDat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayXacNhan DATETIME,
    NgayGiao DATETIME,
    NgayHoanThanh DATETIME,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_DonHang_NguoiDung FOREIGN KEY (IDNguoiDung) REFERENCES NguoiDung(ID) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT FK_DonHang_Voucher FOREIGN KEY (IDVoucher) REFERENCES Voucher(ID) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 15. BẢNG CHI TIẾT ĐƠN HÀNG
CREATE TABLE ChiTietDonHang (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDDonHang INT NOT NULL,
    IDSanPham INT, -- Cho phép NULL khi sản phẩm bị xóa
    TenSanPham VARCHAR(255) NOT NULL, -- Lưu tên tại thời điểm đặt
    SoLuong INT NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,
    ThanhTien DECIMAL(18,2) GENERATED ALWAYS AS (SoLuong * DonGia) STORED,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ChiTietDonHang_DonHang FOREIGN KEY (IDDonHang) REFERENCES DonHang(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_ChiTietDonHang_SanPham FOREIGN KEY (IDSanPham) REFERENCES SanPham(ID) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 17. BẢNG THANH TOÁN
CREATE TABLE ThanhToan (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDDonHang INT NOT NULL,
    MaGiaoDich VARCHAR(100),
    PhuongThucThanhToan VARCHAR(50) NOT NULL,
    SoTien DECIMAL(18,2) NOT NULL,
    TrangThai ENUM('chua_thanh_toan', 'da_thanh_toan', 'that_bai', 'hoan_tien') DEFAULT 'chua_thanh_toan',
    ThongTinThanhToan TEXT, -- JSON chi tiết giao dịch
    NgayThanhToan DATETIME,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_ThanhToan_DonHang FOREIGN KEY (IDDonHang) REFERENCES DonHang(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 18. BẢNG ĐÁNH GIÁ SẢN PHẨM
CREATE TABLE DanhGia (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDSanPham INT NOT NULL,
    IDNguoiDung INT NOT NULL,
    IDDonHang INT,
    SoSao INT NOT NULL CHECK (SoSao BETWEEN 1 AND 5),
    NoiDung VARCHAR(2000),
    HinhAnh VARCHAR(1000), -- Có thể nhiều ảnh, phân cách bằng dấu ","
    TrangThai ENUM('cho_duyet', 'da_duyet', 'an') DEFAULT 'cho_duyet',
    NgayDanhGia DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_DanhGia_SanPham FOREIGN KEY (IDSanPham) REFERENCES SanPham(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_DanhGia_NguoiDung FOREIGN KEY (IDNguoiDung) REFERENCES NguoiDung(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_DanhGia_DonHang FOREIGN KEY (IDDonHang) REFERENCES DonHang(ID) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 19. BẢNG PHẢN HỒI ĐÁNH GIÁ (Admin/Shop reply)
CREATE TABLE PhanHoiDanhGia (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDDanhGia INT NOT NULL,
    IDNguoiDung INT NOT NULL, -- Admin hoặc người có quyền
    NoiDung VARCHAR(2000) NOT NULL,
    NgayPhanHoi DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PhanHoiDanhGia_DanhGia FOREIGN KEY (IDDanhGia)  REFERENCES DanhGia(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_PhanHoiDanhGia_NguoiDung FOREIGN KEY (IDNguoiDung)  REFERENCES NguoiDung(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 20. BẢNG SẢN PHẨM YÊU THÍCH
CREATE TABLE SanPhamYeuThich (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDNguoiDung INT NOT NULL,
    IDSanPham INT NOT NULL,
    NgayThem DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SanPhamYeuThich_NguoiDung FOREIGN KEY (IDNguoiDung) REFERENCES NguoiDung(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SanPhamYeuThich_SanPham FOREIGN KEY (IDSanPham) REFERENCES SanPham(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    UNIQUE KEY unique_wishlist (IDNguoiDung, IDSanPham)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 21. BẢNG LỊCH SỬ TÌM KIẾM
CREATE TABLE LichSuTimKiem (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDNguoiDung INT,
    TuKhoa VARCHAR(255) NOT NULL,
    SoLanTimKiem INT DEFAULT 1,
    NgayTimKiem DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_LichSuTimKiem_NguoiDung FOREIGN KEY (IDNguoiDung) REFERENCES NguoiDung(ID) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

-- 22. BẢNG BANNER QUẢNG CÁO
CREATE TABLE Banner (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TieuDe VARCHAR(255) NOT NULL,
    MoTa VARCHAR(500),
    HinhAnh VARCHAR(1000) NOT NULL,
    LienKet VARCHAR(500),
    ViTri ENUM('trang_chu_chinh', 'trang_chu_phu', 'san_pham', 'sidebar') DEFAULT 'trang_chu_chinh',
    ThuTu INT DEFAULT 0,
    NgayBatDau DATETIME,
    NgayKetThuc DATETIME,
    TrangThai BOOLEAN DEFAULT TRUE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 23. BẢNG THÔNG BÁO
CREATE TABLE ThongBao (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDNguoiDung INT,
    TieuDe VARCHAR(255) NOT NULL,
    NoiDung VARCHAR(1000) NOT NULL,
    LoaiThongBao ENUM('don_hang', 'khuyen_mai', 'he_thong', 'khac') DEFAULT 'he_thong',
    LienKet VARCHAR(500),
    DaDoc BOOLEAN DEFAULT FALSE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ThongBao_NguoiDung FOREIGN KEY (IDNguoiDung) REFERENCES NguoiDung(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 24. BẢNG LIÊN HỆ/HỖ TRỢ KHÁCH HÀNG
CREATE TABLE LienHe (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDNguoiDung INT,
    HoTen VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    SDT VARCHAR(15),
    TieuDe VARCHAR(255) NOT NULL,
    NoiDung VARCHAR(2000) NOT NULL,
    TrangThai ENUM('moi', 'dang_xu_ly', 'da_xu_ly', 'dong') DEFAULT 'moi',
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_LienHe_NguoiDung FOREIGN KEY (IDNguoiDung) REFERENCES NguoiDung(ID) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- INDEX ĐỂ TỐI ƯU QUERY
-- Index cho tìm kiếm sản phẩm
CREATE INDEX idx_sanpham_ten ON SanPham(TenSanPham);
CREATE INDEX idx_sanpham_gia ON SanPham(Gia);
CREATE INDEX idx_sanpham_trangthai ON SanPham(TrangThai);
CREATE INDEX idx_sanpham_loai ON SanPham(IDLoaiSP);
CREATE INDEX idx_sanpham_noibat ON SanPham(NoiBat);

-- Index cho đơn hàng
CREATE INDEX idx_donhang_nguoidung ON DonHang(IDNguoiDung);
CREATE INDEX idx_donhang_trangthai ON DonHang(TrangThai);
CREATE INDEX idx_donhang_ngaydat ON DonHang(NgayDat);
CREATE INDEX idx_donhang_ma ON DonHang(MaDonHang);

-- Index cho đánh giá
CREATE INDEX idx_danhgia_sanpham ON DanhGia(IDSanPham);
CREATE INDEX idx_danhgia_nguoidung ON DanhGia(IDNguoiDung);

-- Index cho giỏ hàng
CREATE INDEX idx_giohang_nguoidung ON GioHang(IDNguoiDung);

-- Index cho voucher
CREATE INDEX idx_voucher_ma ON Voucher(MaVoucher);
CREATE INDEX idx_voucher_trangthai ON Voucher(TrangThai);

-- Index cho tìm kiếm (Đã comment vì bảng LichSuTimKiem đang bị comment)
CREATE INDEX idx_timkiem_tukho ON LichSuTimKiem(TuKhoa);
CREATE INDEX idx_timkiem_nguoidung ON LichSuTimKiem(IDNguoiDung);
